# If this is enabled the plugin will check if the player has his spawnpoint
# set in that world and teleport him there instead of the world spawnpoint or the saved location.
check-for-bed: false

# Customize the messages that are sent by the plugin:
NO-TARGET-SPECIFIED: '&cYou need to specify a target!'
LOCATION-REMOVED-SUCCESS: '&aThe teleport location has been removed successfully.'
LOCATION-SAVED-SUCCESS: '&aThe new teleport location has been set successfully.'
TELEPORT-SUCCESS: '&aYou have been teleported successfully.'
TELEPORT-SUCCESS-WORLD-SPAWN: '&aYou have been teleported at that world''s spawnpoint.'
TELEPORT-SUCCESS-BED-SPAWN: '&aYou have been teleported at your bed spawnpoint.'
TELEPORT-FAIL-TARGET: '&cCould not teleport %player_name%.'
TELEPORT-SUCCESS-TARGET: '&a%player_name% has been teleported successfully.'
TELEPORT-SUCCESS-TARGET-WORLD-SPAWN: '&a%player_name% has been teleported at that world''s spawnpoint.'
TELEPORT-SUCCESS-TARGET-BED-LOCATION: '&a%player_name% has been teleported at this bed spawnpoint.'
WORLD-NOT-SPECIFIED: '&cYou need to specify a world name.'
LOCATION-NOT-FOUND: '&cThere is no location saved in this world.'
NO-PERMISSION: '&cYou do not have permission to do that.'
PLUGIN-RELOADED: '&cPlugin reloaded successfully!'